" Disable Vi settings
set nocompatible

" Add line numbers
set number

" Make tabs equal 2 spaces
set expandtab
set autoindent
set shiftwidth=2
set softtabstop=2

" Enable syntax highlighting
syntax enable

" Enable recognition of indent and plugin files based on filetype
filetype plugin indent on

" Delete trailing whitespace at end of each line on save
autocmd BufWritePre * %s/\s\+$//e

" Move vertically by visual line
nnoremap j gj
nnoremap k gk

" Case insensitive search
set ignorecase

" Forces slower, safer copy + overwrite backing up which also triggers
" Webpack correctly.
" For this issue also remember this:
" https://webpack.github.io/docs/troubleshooting.html#not-enough-watchers
set backupcopy=yes

